### ISSUE TITLE
Can't connect to API issue

### ISSUE THREAD

**Issue by Zeunas** [natekspencer/hacs-litterrobot#11]
Following the new HA update (6.2) integration can't connect with API.

Let me know what you need to investigate this further.

**Comment by flyize** [comment]
I have the same issue

**Comment by natekspencer** [comment]
Latest release of HomeAssistant bumps httpx to 0.18.2 which introduced a breaking change that the underlying auth library pylitterbot uses (Authlib) hasn't released to address yet.

I'm working on a fix in my dependency for now:
 - https://github.com/natekspencer/pylitterbot/issues/4

**Comment by flyize** [comment]
Looks like you fixed it. Any idea how long before it gets into HA?

**Comment by natekspencer** [comment]
@flyize HA 2021.8.2 is out today which includes this fix.
