### ISSUE TITLE
Request: any change there will be a version for Homey?

### ISSUE THREAD

**Issue by Phusebox** [natekspencer/hacs-litterrobot#15]
Would be great if we could integrate this with Homey as well...

**Comment by natekspencer** [comment]
I don't own a Homey and it looks like it uses Node.js for developer integrations. So while I'm potentially capable of doing so, I don't have the bandwidth, motivation nor the Homey to be able to test and support it at this time.

**Comment by flyize** [comment]
What is a Homey? My Google-fu failed me.

**Comment by Phusebox** [comment]
https://homey.app/en-us/
It's a smart home hub/device
