### ISSUE TITLE
Feeder Robot - Not an issue

### ISSUE THREAD

**Issue by oliverhartley** [natekspencer/hacs-litterrobot#16]
Hi!
Awsome work with the litter robot integration!!
Is it posible to do the same with the feeder?

https://www.litter-robot.com/feeder-robot.html

**Comment by natekspencer** [comment]
Thank you. The problem currently is not being able to test since I don't own one yet. But I'm working on that and once I have one I'll attempt to expand it to this.

**Comment by natekspencer** [comment]
Feeder-robot is now supported in the official integration.
